import { LegalShell } from "@/components/layout/LegalShell";

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service">
      <p>
        These terms govern access to and use of Jobform, including the customer support portal, staff console,
        integrations, and related software. By using Jobform, you agree to these terms.
      </p>

      <h2>The service</h2>
      <p>
        Jobform is a customer-support product for refund requests. An AI agent may converse with a customer, look up
        order context, and select tools. Deterministic Jobform server code decides refund eligibility, amount, and
        ledger writes. The language model does not have financial authority.
      </p>

      <h2>Accounts and access</h2>
      <p>
        Staff access requires credentials issued by the workspace owner. You must keep those credentials confidential
        and notify the workspace owner of unauthorized use. Customers may open support by verifying an email and order
        ID, or through a signed launch from a connected store. You may not attempt to access another customer’s orders
        or the staff console without authorization.
      </p>

      <h2>Customer and order data</h2>
      <p>
        The organization deploying Jobform is responsible for the accuracy of customer and order data supplied to the
        product, including data synchronized from a commerce platform. Jobform evaluates refunds against that data and
        the published refund policy. Jobform is not responsible for incorrect source records, unpublished policy
        changes, or store-side fulfillment errors.
      </p>

      <h2>Refunds and payments</h2>
      <p>
        An approved refund in Jobform is a record in the Jobform ledger. It is not, by itself, a transfer of funds.
        Settlement to the original payment method requires a connected payment provider configured by the deploying
        organization. Until that provider is connected, Jobform does not move money at a bank or card network.
      </p>

      <h2>AI-generated output</h2>
      <p>
        Agent replies, summaries, and spoken responses are generated by artificial intelligence and may be inaccurate
        or incomplete. Voice output is AI-generated. Customers and staff should treat agent explanations as assistance,
        not as a substitute for the recorded policy decision or ledger entry. Jobform discloses AI-generated voice in
        the support interface.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not submit payment-card data, passwords, or other secrets in support chat.</li>
        <li>Do not probe, disrupt, or overload the service, or attempt to bypass access controls.</li>
        <li>Do not use Jobform to violate law, infringe rights, or process data you are not authorized to process.</li>
        <li>Do not reverse engineer the product except where applicable law allows it.</li>
      </ul>

      <h2>Availability and changes</h2>
      <p>
        We may modify, suspend, or discontinue features. We do not guarantee uninterrupted availability. You are
        responsible for backups, monitoring, and incident response for workspaces you operate.
      </p>

      <h2>Intellectual property</h2>
      <p>
        Jobform, its software, and its branding remain the property of their owners. You retain rights in customer and
        order data you submit. You grant Jobform a limited license to process that data solely to provide the service.
      </p>

      <h2>Disclaimer</h2>
      <p>
        Jobform is provided “as is.” To the fullest extent permitted by law, we disclaim warranties of merchantability,
        fitness for a particular purpose, and non-infringement. We do not warrant that refund decisions will match every
        business, legal, or payment-network outcome.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, Jobform and its operators are not liable for indirect, incidental,
        special, consequential, or lost-profit damages, or for amounts already recorded or denied in the refund ledger,
        arising from use of the service. Some jurisdictions do not allow certain limitations, in which case those
        limitations apply only to the extent permitted.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms. The effective date at the top of this page will change when we do. Continued use
        after an update constitutes acceptance of the revised terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms should be directed to the organization operating the Jobform workspace you used.
      </p>
    </LegalShell>
  );
}
